name: AWS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: Build
      run: dotnet build -c Release -o out
#    - name: Cache
#      uses: actions/cache@v1.1.0
#      with:
#        path: cache
#        key: AR-${{ hashFiles('obj/**') }}
#        restore-keys: AR-
    - name: Run
      run: out/DDB
      env:
        KEY: ${{ secrets.KEY }}
